# Setup (do this once after cloning):
# 1. Rename this file to config.properties
# 2. Replace the paths below with your own

opencv.lib.path=/Users/chengchijiang/CodingEnvironment/opencv/build/lib/libopencv_java4130.dylib
video.dir=/Users/chengchijiang/NEU CSA/CS5004/GitHub/asl-recognition-framework/assets/guidance/
camera.url=http://10.20.9.211:4747/video
